source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

target 'Repository_Example' do
  
  pod 'SwiftRepository', :path => '../'
  pod 'KeychainSwift'
  pod 'RealmSwift'
  
  target 'Repository_Tests' do
    inherit! :search_paths

  end
end
